privatelift:
  dependency:
    PrivateLiftInstanceRepository:
      class: fbpmp.private_lift.repository.privatelift_instance_local.LocalPrivateLiftInstanceRepository
      constructor:
        base_dir: /fbpmp_instances
    ContainerService:
      class: fbpcp.service.container_aws.AWSContainerService
      constructor:
        region: TODO
        cluster: TODO
        subnets: [TODO]
        access_key_id: TODO
        access_key_data: TODO
    StorageService:
      class: fbpcp.service.storage_s3.S3StorageService
      constructor:
        region: TODO
        access_key_id: TODO
        access_key_data: TODO
    ValidationConfig:
      is_validating: false
      synthetic_shard_path: TODO
    OneDockerBinaryConfig:
      default:
        constructor:
          tmp_directory: /tmp
          binary_version: latest
    OneDockerServiceConfig:
      constructor:
        task_definition: TODO_ONEDOCKER_TASK_DEFINITION
pid:
  dependency:
    ShardingService:
      class: fbpmp.data_processing.sharding.sharding_cpp.CppShardingService
    PIDInstanceRepository:
      class: fbpmp.pid.repository.pid_instance_local.LocalPIDInstanceRepository
      constructor:
        base_dir: /fbpmp_instances
  CloudCredentialService:
    class: fbpmp.pid.service.credential_service.simple_cloud_credential_service.SimpleCloudCredentialService
    constructor:
      access_key_id: TODO
      access_key_data: TODO
mpc:
  dependency:
    MPCGameService:
      class: fbpcp.service.mpc_game.MPCGameService
      dependency:
        PrivateLiftGameRepository:
          class: fbpmp.private_lift.repository.private_lift_game.PrivateLiftGameRepository
    MPCInstanceRepository:
      class: fbpcp.repository.mpc_instance_local.LocalMPCInstanceRepository
      constructor:
        base_dir: /fbpmp_instances
    ShardingService:
      class: fbpmp.data_processing.sharding.sharding_cpp.CppShardingService
graphapi:
  access_token: TODO
