[package]
name = "kodiak"
version = "0.0.0"
edition = "2021"

[dependencies]
derive_more = "0.99.3"
lazy_static = "1.0"
log = { version = "0.4.14", features = ["kv_unstable", "kv_unstable_std"] }
petgraph = "0.6"
regex = "1.5.4"
