name: Build and Publish Data Processing and EMP Games Docker Images

on:
  push:
    branches: [ main ]

env:
  FBPCF_VERSION: 2.1.78  # Please also update line 29 in .github/workflows/docker-publish.yml
  REGISTRY: ghcr.io

jobs:
  output_version:
    runs-on: ubuntu-latest
    name: Set FBPCF version
    outputs:
      fbpcf_version: ${{ steps.set_version.outputs.version }}
    steps:
      - id: set_version
        run: echo "version=${{ env.FBPCF_VERSION }}" >> $GITHUB_OUTPUT

  build_and_publish_data_processing_image:
    name: Build and Publish Data Processing Image
    needs: output_version
    uses: ./.github/workflows/build_binary_image.yml
    with:
      image_to_build: data_processing
      tag: latest
      fbpcf_version: ${{needs.output_version.outputs.fbpcf_version}}
      push_to_registry: true

  build_and_publish_emp_games_image:
    name: Build and Publish EMP Games Image
    needs: output_version
    uses: ./.github/workflows/build_binary_image.yml
    with:
      image_to_build: emp_games
      tag: latest
      fbpcf_version: ${{needs.output_version.outputs.fbpcf_version}}
      push_to_registry: true
