name: Create Hotfix

on:
  workflow_dispatch:
    inputs:
      branch_name:
        description: "The name of the branch to create where the hotfix will live"
        required: true
        type: string
      base_commit:
        description: "Commit hash on which to base the changes"
        required: true
        type: string
      hotfix_commit:
        description: "Commit to patch into the base revision"
        required: true
        type: string
      tracker_hash:
        description: "[Internal usage] Used for tracking workflow job status within Meta infra"
        required: false
        type: string

env:
  PROD_REGISTRY_IMAGE_NAME: ghcr.io/facebookresearch/fbpcs/coordinator
  PROD_TAG: latest

jobs:
  create_hotfix:
    name: Create hotfix commit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Print Tracker Hash
        run: echo ${{ github.event.inputs.tracker_hash }}

      - name: Create hotfix commit on new branch
        run: |
          git config --global user.name "GithubActions CreateHotfix"
          git config --global user.email "pc_release@fb.com"
          git remote set-url origin https://${{ secrets.OMNI_PERSONAL_ACCESS_TOKEN }}@github.com/facebookresearch/fbpcs.git
          git checkout ${{ github.event.inputs.base_commit }} -b ${{ github.event.inputs.branch_name }}
          git cherry-pick ${{ github.event.inputs.hotfix_commit }}
          echo "------------------------- Created patch -------------------------"
          git diff HEAD^
          echo "--------------------------- End patch ---------------------------"
          git push -u origin ${{ github.event.inputs.branch_name }}
